EXIT as soon as something fails.

diff --git a/chroot_objects/chroot_objects b/chroot_objects/chroot_objects
--- a/chroot_objects/chroot_objects
+++ b/chroot_objects/chroot_objects
@@ -1,6 +1,6 @@
 #!/bin/sh
 # 
-# $Id: chroot_objects,v 1.13 2007/09/23 20:56:22 iku Exp $
+# $Id: chroot_objects,v 1.14 2007/09/23 20:57:33 iku Exp $
 #
 # Copyright (c) 2007 Antti Harri <iku@openbsd.fi>
 #
@@ -52,11 +52,11 @@ parse()
 				grp=$(echo "$stat" | awk '{ print $6 }' | cut -f 2 -d '=')
 				uid=$(echo "$stat" | awk '{ print $5 }' | cut -f 2 -d '=')
 				mode=$(echo "$stat" | awk '{ print $3 }' | cut -b 11-)
-				install -d -g "$grp" -o "$uid" -m "$mode" "${1}${i}"
+				install -d -g "$grp" -o "$uid" -m "$mode" "${1}${i}" || (echo "FAILED" ; exit)
 			done
 			unset IFS
 			#mkdir -p "${1}/./${dir}/"
-			cp -p "$lib" "${1}/./${dir}/"
+			cp -p "$lib" "${1}/./${dir}/" || (echo "FAILED" ; exit)
 			echo "${3}${lib}"
 			parse "$1" "$lib" "$3  "
 		fi
